repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ --autofix, --indent=4]
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
  - repo: https://github.com/chewse/pre-commit-mirrors-pydocstyle
    rev: v2.1.1
    hooks:
      - id: pydocstyle
        args: ['--ignore=D1,D203,D212']
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
      - id: pylint
        args: ['--ignore=migrations,env.py']
exclude: 'docs'
